spring:
  datasource:
    url: jdbc:mysql://localhost:3306/networkdetails
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Automatically updates the database schema based on your entities
    show-sql: true  # Shows SQL statements in the logs

server:
  port: 8080  # Server port
